name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Allows pushing changes to the repository
  pull-requests: write  # Allows creating releases

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for creating releases

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2
      # with:
      #   token: ''
    

    # Step 2: Set up Node.js (for running semantic-release)
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'  # Use latest LTS version of Node.js

    # Step 3: Install dependencies (if you have any, e.g., your Node.js app dependencies)
    - name: Install dependencies
      run: npm install

    # Step 4: Install semantic-release and plugins
    - name: Install semantic-release and plugins
      run: npm install --save-dev semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github -d

    # Step 5: Run semantic-release
    - name: Run semantic-release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure GitHub token is passed to semantic-release